(() => {
  const P=window.PFV3;
  const demo=()=>({id:'PF-DEMO-2048',createdAt:new Date(Date.now()-86400000).toISOString(),stage:Number(localStorage.getItem('pfDemoStageV3')||2),vehicle:'Toyota Corolla 2013 · 1.6 Petrol',payment:'Pay on Pickup',provisionalTotal:295,confirmedTotal:285,items:[{name:'DENSO K16TT Spark Plug',price:35,qty:4},{name:'Spin-On Engine Oil Filter',price:50,qty:1},{name:'Engine Air Filter',price:85,qty:1}],demo:true});
  function demoTools(o){if(o.demo||sessionStorage.getItem('pfSafeDemo')!=='1')return '';return `<section class="prototypeControl"><div><b>End-to-end test controls</b><p>These buttons change only this browser's demo order. Production staff approval happens on the protected backend.</p></div><div class="field"><label>Test confirmed amount (GH₵)</label><input id="demoConfirmedPrice" inputmode="decimal" value="${o.confirmedTotal??o.provisionalTotal??0}"></div><div class="row"><button class="btn outlineNavy" data-demo-stage="1" data-id="${P.esc(o.id)}">Under Review</button><button class="btn red" data-demo-stage="2" data-id="${P.esc(o.id)}">Approve</button><button class="btn dark" data-demo-stage="3" data-id="${P.esc(o.id)}">Ready</button><button class="btn outlineNavy" data-demo-stage="4" data-id="${P.esc(o.id)}">Collected</button></div></section>`}
  function page(id=''){
    if(!id){app.innerHTML=appHeader('Track an Order','Order reference · status')+`<main class="page"><section class="lookupHero"><span class="sectionKicker">TRACKING</span><h1>Where is my order?</h1><p>Enter your PartFit reference.</p></section><section class="card lookupCard"><div class="field"><label>Order reference</label><input id="v3TrackRef" placeholder="PF-260813-123"></div><button class="btn red full" data-v3-track-submit>Track Order</button><button class="textAction" data-v3-demo>View demo tracking</button></section>${P.footer()}</main>${nav('orders')}`;return}
    const o=id==='PF-DEMO-2048'?demo():P.orders().find(x=>x.id===id);
    if(!o){page();say('Order not found on this device');return}
    const s=Math.min(4,Number(o.stage||0));
    app.innerHTML=appHeader('Track Order',o.id)+`<main class="page"><section class="v3TrackHero"><div><span class="sectionKicker">${o.demo?'DEMO TRACKING':'ORDER STATUS'}</span><h1>${P.esc(o.id)}</h1><p>${P.fmt(o.createdAt)} · Pay on Pickup</p></div><div><small>Current status</small><b>${P.esc(P.steps[s])}</b></div></section><section class="card v3Timeline">${P.steps.map((x,i)=>`<div class="v3Step ${i<=s?'done':''} ${i===s?'current':''}"><span>${i<=s?'✓':i+1}</span><div><b>${P.esc(x)}</b><small>${i<s?'Completed':i===s?'Current':'Pending'}</small></div></div>`).join('')}</section><section class="v3ApprovalAmount"><div><small>${o.confirmedTotal!=null?'Approved amount due at pickup':'Provisional basket total'}</small><b>${money(Number(o.confirmedTotal??o.provisionalTotal??0))}</b></div><p>${o.confirmedTotal!=null?'This is the amount to pay when collecting your approved order.':'No payment is due yet. Wait for PartFit approval and the confirmed price.'}</p></section>${o.demo?`<section class="prototypeControl"><div><b>Prototype preview</b><p>Advance the sample order to see each customer status.</p></div><button class="btn dark" data-v3-advance>Advance Status</button></section>`:demoTools(o)}${P.footer()}</main>${nav('orders')}`;
  }
  P.register('track',page);
  document.addEventListener('click',e=>{
    if(e.target.closest('[data-v3-demo]')){render('track','PF-DEMO-2048');return}
    if(e.target.closest('[data-v3-track-submit]')){const id=(document.getElementById('v3TrackRef')?.value||'').trim().toUpperCase();id?render('track',id):say('Enter an order reference');return}
    if(e.target.closest('[data-v3-advance]')){localStorage.setItem('pfDemoStageV3',String((Number(localStorage.getItem('pfDemoStageV3')||2)+1)%5));page('PF-DEMO-2048');return}
    const b=e.target.closest('[data-demo-stage]');if(b){const list=P.orders(),o=list.find(x=>x.id===b.dataset.id);if(!o)return;o.stage=Number(b.dataset.demoStage);if(o.stage>=2){const val=Number(document.getElementById('demoConfirmedPrice')?.value);if(Number.isFinite(val)&&val>0)o.confirmedTotal=val}P.write(P.keys.orders,list);say('Demo order status updated');page(o.id)}
  },true);
})();