/* PartFit Ghana V3 account/profile preview */
(() => {
  const P=window.PFV3;
  function authPage(mode){const up=mode==='signup';app.innerHTML=appHeader(up?'Create Account':'Sign In',up?'Orders · saved cars · tracking':'Prototype profile on this device')+`<main class="page v3Auth"><section class="v3AuthPitch"><span class="sectionKicker">PARTFIT ACCOUNT</span><h1>${up?'Your garage and orders, remembered.':'Welcome back.'}</h1><p>${up?'Create a profile to save vehicles and keep order history.':'Use the email from the profile created on this device.'}</p><div><b>🚗 Saved vehicles</b><b>🧾 Order history</b><b>📦 Fulfilment tracking</b></div></section><section class="card v3AuthCard">${up?`<div class="field"><label>Full name *</label><input id="v3Name" autocomplete="name"></div><div class="field"><label>Phone / WhatsApp *</label><input id="v3Phone" autocomplete="tel"></div>`:''}<div class="field"><label>Email *</label><input id="v3Email" type="email" autocomplete="email"></div><button class="btn red full big" data-v3-profile="${mode}">${up?'Create My Account':'Sign In'}</button><div class="prototypeNotice"><b>Prototype only</b><span>This preview stores the profile on this device and uses email-only demo sign-in. Production will use secure backend authentication.</span></div><button class="textAction" data-page="${up?'login':'signup'}">${up?'Already have a profile? Sign in':'New to PartFit? Create an account'}</button></section>${P.footer()}</main>${nav('account')}`}
  function login(){P.signed()?account():authPage('login')}
  function signup(){P.signed()?account():authPage('signup')}
  function orderMini(o){return `<div class="v3OrderMini"><span>📦</span><div><b>${P.esc(o.id)}</b><small>${P.fmt(o.createdAt)} · ${P.esc(P.steps[o.stage]||P.steps[0])}</small></div><div><b>${money(Number(o.total||0))}</b><button data-v3-track="${P.esc(o.id)}">Track</button></div></div>`}
  function account(){if(!P.signed()){login();return}const p=P.profile(),orders=P.userOrders(),cars=P.cars();app.innerHTML=appHeader('My Account','Profile · vehicles · orders')+`<main class="page"><section class="v3DashHero"><div class="v3Avatar">${P.initials(p.name)}</div><div><span class="sectionKicker">MY PARTFIT</span><h1>${P.esc(p.name)}</h1><p>${P.esc(p.email)} · ${P.esc(p.phone)}</p></div><button class="btn outlineNavy" data-v3-logout>Sign Out</button></section><section class="v3Stats"><button data-page="orders"><b>${orders.length}</b><small>Total orders</small></button><button data-page="orders"><b>${orders.filter(x=>x.stage<4).length}</b><small>Open orders</small></button><button><b>${cars.length}</b><small>Saved cars</small></button></section><section class="v3DashGrid"><div class="card v3Panel"><div class="head"><h2>Recent orders</h2><button class="link" data-page="orders">View all</button></div>${orders.length?orders.slice(0,3).map(orderMini).join(''):`<div class="empty"><h2>No orders yet</h2><button class="btn red" data-page="catalogue">Browse Parts</button></div>`}</div><div class="card v3Panel"><div class="head"><h2>Saved vehicles</h2>${S.vehicle?`<button class="link" data-v3-save-car>+ Save current</button>`:''}</div>${cars.length?cars.map((c,i)=>`<div class="v3SavedCar"><span>🚗</span><div><b>${P.esc(c.make+' '+c.model)}</b><small>${P.esc(c.year+' · '+c.engine)}</small></div><button data-v3-use-car="${i}">Use</button><button data-v3-remove-car="${i}">×</button></div>`).join(''):`<div class="empty"><p>No saved vehicles yet.</p><button data-page="vehicle">Select My Car</button></div>`}</div></section><section class="sec v3AccountTools"><button data-page="contact">💬 <b>Support</b><small>Order & fitment help</small></button><button data-page="faq">? <b>FAQ</b><small>Common questions</small></button><button data-page="fitment">✓ <b>Fitment Policy</b><small>How compatibility works</small></button></section>${P.footer()}</main>${nav('account')}`}
  P.register('login',login);P.register('signup',signup);P.register('account',account);

  document.addEventListener('click',e=>{
    const a=e.target.closest('[data-v3-profile]');if(a){const mode=a.dataset.v3Profile,email=(document.getElementById('v3Email')?.value||'').trim().toLowerCase();if(!email.includes('@')){say('Enter a valid email');return}if(mode==='signup'){const name=(document.getElementById('v3Name')?.value||'').trim(),phone=(document.getElementById('v3Phone')?.value||'').trim();if(!name||!phone){say('Enter your name and phone');return}P.write(P.keys.profile,{name,phone,email});localStorage.setItem(P.keys.signed,'1');if(S.vehicle)P.write(P.keys.cars,[S.vehicle]);say('Account created');account();P.setHash('account')}else{const p=P.profile();if(!p||p.email!==email){say('No prototype profile with that email exists on this device');return}localStorage.setItem(P.keys.signed,'1');say('Signed in');account();P.setHash('account')}return}
    if(e.target.closest('[data-v3-logout]')){localStorage.setItem(P.keys.signed,'0');say('Signed out');render('home');return}
    if(e.target.closest('[data-v3-save-car]')){if(!S.vehicle){say('Select a vehicle first');return}const c=P.cars();if(!c.some(x=>JSON.stringify(x)===JSON.stringify(S.vehicle))){c.push(S.vehicle);P.write(P.keys.cars,c)}account();return}
    const use=e.target.closest('[data-v3-use-car]');if(use){const c=P.cars()[Number(use.dataset.v3UseCar)];if(c){S.vehicle=c;save();render('catalogue')}return}
    const rem=e.target.closest('[data-v3-remove-car]');if(rem){const c=P.cars();c.splice(Number(rem.dataset.v3RemoveCar),1);P.write(P.keys.cars,c);account();return}
  },true);
})();
