/* PartFit Ghana safe demo account portal */
(() => {
 const P=window.PFV3,baseProfile=P.profile,baseSigned=P.signed;
 const demo={name:'Demo Customer',email:'demo.customer@partfit.local',phone:'055 000 0000'};
 P.profile=()=>sessionStorage.getItem('pfSafeDemo')==='1'?demo:baseProfile();
 P.signed=()=>sessionStorage.getItem('pfSafeDemo')==='1'||baseSigned();
 function login(){app.innerHTML=appHeader('My PartFit','Safe end-to-end test session')+`<main class="page"><section class="v3AuthPitch"><span class="sectionKicker">TEST ACCOUNT</span><h1>Try the full customer journey safely.</h1><p>Use a non-sensitive Demo Customer session to test My Garage, orders, approval prices and pickup tracking. No real credentials are requested on GitHub Pages.</p><div><b>🚗 My Garage</b><b>🧾 Order history</b><b>📦 Pickup tracking</b></div></section><section class="card v3AuthCard"><button class="btn red full big" data-demo-customer>Continue as Demo Customer</button><div class="prototypeNotice"><b>Production authentication</b><span>The repository contains the Supabase/RLS backend design. Real customer authentication should only be enabled after the backend project and security policies are deployed.</span></div></section>${P.footer()}</main>${nav('account')}`}
 function orderMini(o){return `<div class="v3OrderMini"><span>📦</span><div><b>${P.esc(o.id)}</b><small>${P.fmt(o.createdAt)} · ${P.esc(P.steps[o.stage]||P.steps[0])}</small></div><div><b>${money(Number(o.total||0))}</b><button data-v3-track="${P.esc(o.id)}">Track</button></div></div>`}
 function account(){if(!P.signed())return login();const p=P.profile(),orders=P.userOrders(),cars=P.cars();app.innerHTML=appHeader('My PartFit','Profile · My Garage · orders')+`<main class="page"><section class="v3DashHero"><div class="v3Avatar">DC</div><div><span class="sectionKicker">DEMO CUSTOMER</span><h1>${P.esc(p.name)}</h1><p>Safe test session · no real credentials</p></div><button class="btn outlineNavy" data-demo-logout>Exit Demo</button></section><section class="v3Stats"><button data-page="orders"><b>${orders.length}</b><small>Total orders</small></button><button data-page="orders"><b>${orders.filter(x=>x.stage<4).length}</b><small>Open orders</small></button><button><b>${cars.length}</b><small>Garage vehicles</small></button></section><section class="v3DashGrid"><div class="card v3Panel"><div class="head"><h2>Recent orders</h2><button class="link" data-page="orders">View all</button></div>${orders.length?orders.slice(0,3).map(orderMini).join(''):`<div class="empty"><p>No orders yet.</p><button class="btn red" data-page="catalogue">Browse Parts</button></div>`}</div><div class="card v3Panel"><div class="head"><h2>My Garage</h2>${S.vehicle?`<button class="link" data-demo-save-car>+ Save current</button>`:''}</div>${cars.length?cars.map((c,i)=>`<div class="v3SavedCar"><span>🚗</span><div><b>${P.esc(c.make+' '+c.model)}</b><small>${P.esc(c.year+' · '+c.engine)}</small></div><button data-demo-use-car="${i}">Shop</button><button data-demo-remove-car="${i}">×</button></div>`).join(''):`<div class="empty"><p>No vehicles saved yet.</p><button data-page="vehicle">Select My Car</button></div>`}</div></section>${P.footer()}</main>${nav('account')}`}
 P.register('login',login);P.register('signup',login);P.register('account',account);
 document.addEventListener('click',e=>{if(e.target.closest('[data-demo-customer]')){sessionStorage.setItem('pfSafeDemo','1');say('Demo customer ready');account();return}if(e.target.closest('[data-demo-logout]')){sessionStorage.removeItem('pfSafeDemo');say('Demo session ended');render('home');return}if(e.target.closest('[data-demo-save-car]')){if(!S.vehicle)return say('Select a vehicle first');const c=P.cars();if(!c.some(x=>JSON.stringify(x)===JSON.stringify(S.vehicle))){c.push(S.vehicle);P.write(P.keys.cars,c)}account();return}const u=e.target.closest('[data-demo-use-car]');if(u){const c=P.cars()[Number(u.dataset.demoUseCar)];if(c){S.vehicle=c;save();render('catalogue')}return}const r=e.target.closest('[data-demo-remove-car]');if(r){const c=P.cars();c.splice(Number(r.dataset.demoRemoveCar),1);P.write(P.keys.cars,c);account()}},true);
})();