(() => {
 const A=PartFitApp,U=PartFitUtil,C=PARTFIT_CONFIG,Store=PartFitStore;
 A.refreshUser=async()=>{A.user=await Store.currentUser();return A.user};
 A.requireUser=async(returnTo='account')=>{await A.refreshUser();if(A.user)return true;sessionStorage.setItem('pf5_return',returnTo);await A.route('login');return false};
 A.route=async(name='home',arg='',setHash=true)=>{const fn=A.pages[name]||A.pages.home;if(!fn)return;if(setHash)history.replaceState(null,'','#'+name+(arg?':'+encodeURIComponent(arg):''));document.getElementById('app').innerHTML='<div class="pfLoading">Loading…</div>';try{await fn(arg)}catch(e){console.error(e);document.getElementById('app').innerHTML=A.page(`<section class="pfError"><h1>Something went wrong</h1><p>${U.esc(e.message||'Please try again.')}</p><button class="pfBtn navy" data-route="home">Back home</button></section>`,'home')}window.scrollTo({top:0,behavior:'instant'})};
 document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){e.preventDefault();A.route(r.dataset.route,r.dataset.arg||'');return}const h=e.target.closest('[data-help]');if(h){e.preventDefault();U.whatsapp(C.businessWhatsApp,'Hello PartFit Ghana, I need assistance with a car part or order.');return}const add=e.target.closest('[data-add]');if(add){e.preventDefault();A.addCart(add.dataset.add);A.route('cart');return}const ins=e.target.closest('[data-install]');if(ins){e.preventDefault();if(A.installPrompt){A.installPrompt.prompt();A.installPrompt.userChoice.finally(()=>A.installPrompt=null)}else A.toast('Use your browser menu → Add to Home Screen')}});
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();A.installPrompt=e});
 window.addEventListener('hashchange',()=>{const [p,...rest]=location.hash.slice(1).split(':');if(p&&A.pages[p])A.route(p,decodeURIComponent(rest.join(':')||''),false)});
 A.start=async()=>{await Store.init();await A.refreshUser();const [p,...rest]=location.hash.slice(1).split(':');await A.route(A.pages[p]?p:'home',decodeURIComponent(rest.join(':')||''),false);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)};
})();